creation_rules:
  - path_regex: 'secrets/database/.*\.yaml$'
    age: age19wlm28gh6wxvs30yq7rm2yprz6n79ju7lyshn37sfjm790q30tstkmndv

  - path_regex: 'k8s/secrets/.*\.yaml$'
    encrypted_regex: '^(data|stringData)$'
    age: age19wlm28gh6wxvs30yq7rm2yprz6n79ju7lyshn37sfjm790q30tstkmndv
